##
## Build
##
FROM golang:1.17.6-alpine as builder

ENV ROOT=/go/src/app

WORKDIR ${ROOT}

RUN apk update \
    && apk add git curl

RUN cp -a ./src/app/go.mod ./src/app/go.sum ./src/app/go.sum ./

RUN go mod tidy

RUN cp -a ./src/app ${ROOT}
RUN CGO_ENABLED=0 GOOS=linux go build -o $ROOT/binary

##
## Deploy
##
FROM scratch as prod

ENV ROOT=/go/src/app
WORKDIR ${ROOT}
COPY --from=builder ${ROOT}/binary ${ROOT}

ENV PORT=${PORT}
CMD ["/go/src/app/binary"]